# Sources Overlap graphs

#### Since the pie charts are too busy and don't give enough information, try for a network graph using pyvis.

#### Want to import from the google sheet or at least a version of it that sn't too far off. Could import as a matrix, the rows and column headers are nodes, and the existance of items in cells are edges. Would be great to colour attributes and features by essential element, and to have their relative size dictated by the number of edges connected to them.

In [25]:
import pandas as pd
import numpy as np
from scipy import sparse
import networkx as nx
from pyvis.network import Network

In [31]:
df = pd.read_excel('SourcesOverlapNetwork1.xlsx', dtype=int)
print(df.values)

[[1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


#### This is a bipartite graph (https://en.wikipedia.org/wiki/Bipartite_graph), following the suggestion here: https://stackoverflow.com/questions/59862598/importing-non-square-adjacency-matrix-into-networkx-python

In [33]:
sm = sparse.csr_matrix(df.values)
graphdata = nx.algorithms.bipartite.matrix.from_biadjacency_matrix(sm)

# visualize it with pyvis
Netdata = Network(height='800px', width='100%', bgcolor='#222222', font_color='white',notebook=True)
Netdata.barnes_hut()
for n in graphdata.nodes:
    Netdata.add_node(int(n))
for e in graphdata.edges:
    Netdata.add_edge(int(e[0]), int(e[1]))
    
Netdata.write_html('SourcesOverlap.html')

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


## Test

#### From https://stackoverflow.com/questions/63492418/plotting-a-graph-with-neworkx-using-a-csv-file-as-co-occurence-matrix

In [11]:
# creating a dummy adjacency matrix of shape 20x20 with random values of 0 to 3
adj_mat = np.random.randint(0, 3, size=(20, 20))
np.fill_diagonal(adj_mat, 0)  # setting the diagonal values as 0
dftest = pd.DataFrame(adj_mat)

# create a graph from your dataframe
G = nx.from_pandas_adjacency(dftest)

# visualize it with pyvis
N = Network(height='100%', width='100%', bgcolor='#222222', font_color='white',notebook=True)
N.barnes_hut()
for n in G.nodes:
    N.add_node(int(n))
for e in G.edges:
    N.add_edge(int(e[0]), int(e[1]))

#N.write_html('coocc-graph.html')
N.show('coocc-graph.html')

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [12]:
print(dftest)

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    0   0   1   1   2   2   0   2   0   2   2   1   0   1   1   1   0   2   
1    1   0   1   1   1   1   0   0   1   1   0   1   0   1   0   2   1   2   
2    2   1   0   0   2   2   2   2   2   1   2   0   1   2   2   1   0   0   
3    2   2   1   0   2   1   1   1   2   0   2   0   2   0   1   1   2   0   
4    1   2   1   1   0   0   1   2   2   2   1   1   2   1   1   2   1   0   
5    1   1   1   0   2   0   0   1   2   2   0   1   1   1   0   1   1   0   
6    2   2   2   2   2   0   0   0   0   2   2   0   0   1   2   2   0   2   
7    2   0   0   2   1   0   0   0   1   0   0   1   0   0   0   2   1   1   
8    0   2   0   1   2   0   0   0   0   0   2   2   2   2   0   1   1   1   
9    0   2   1   2   2   2   1   2   2   0   1   1   1   0   2   2   0   1   
10   2   0   0   0   1   0   0   1   0   0   0   2   0   2   2   1   2   1   
11   0   0   0   1   1   2   1   0   0   1   2   0   0   0   1  

In [13]:
print(G)

Graph with 20 nodes and 166 edges


In [19]:
print(adj_mat)

[[0 0 1 1 2 2 0 2 0 2 2 1 0 1 1 1 0 2 2 2]
 [1 0 1 1 1 1 0 0 1 1 0 1 0 1 0 2 1 2 0 0]
 [2 1 0 0 2 2 2 2 2 1 2 0 1 2 2 1 0 0 2 2]
 [2 2 1 0 2 1 1 1 2 0 2 0 2 0 1 1 2 0 0 1]
 [1 2 1 1 0 0 1 2 2 2 1 1 2 1 1 2 1 0 0 2]
 [1 1 1 0 2 0 0 1 2 2 0 1 1 1 0 1 1 0 1 0]
 [2 2 2 2 2 0 0 0 0 2 2 0 0 1 2 2 0 2 1 2]
 [2 0 0 2 1 0 0 0 1 0 0 1 0 0 0 2 1 1 2 2]
 [0 2 0 1 2 0 0 0 0 0 2 2 2 2 0 1 1 1 0 2]
 [0 2 1 2 2 2 1 2 2 0 1 1 1 0 2 2 0 1 2 0]
 [2 0 0 0 1 0 0 1 0 0 0 2 0 2 2 1 2 1 0 2]
 [0 0 0 1 1 2 1 0 0 1 2 0 0 0 1 1 2 1 0 0]
 [1 1 2 1 0 2 2 0 0 1 1 2 0 1 0 1 1 0 0 2]
 [0 2 1 1 1 0 1 0 2 1 2 1 1 0 2 2 1 1 2 0]
 [1 2 2 0 2 1 2 1 0 1 0 2 1 0 0 0 0 1 0 0]
 [2 1 2 0 0 0 1 1 0 1 2 2 0 0 2 0 2 1 1 1]
 [1 2 2 2 1 1 2 0 2 2 0 1 2 2 2 0 0 1 1 0]
 [0 0 2 1 0 0 0 2 1 1 1 2 0 0 0 2 1 0 1 2]
 [0 0 2 0 0 0 1 1 0 2 0 0 2 0 0 1 0 0 0 1]
 [0 1 2 1 0 2 1 0 0 1 0 0 0 0 0 1 2 2 0 0]]


In [14]:
for n in G.nodes:
    print(n)
for e in G.edges:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 7)
(0, 9)
(0, 10)
(0, 11)
(0, 13)
(0, 14)
(0, 15)
(0, 17)
(0, 18)
(0, 19)
(0, 1)
(0, 6)
(0, 12)
(0, 16)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 8)
(1, 9)
(1, 11)
(1, 13)
(1, 15)
(1, 16)
(1, 17)
(1, 6)
(1, 12)
(1, 14)
(1, 19)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(2, 9)
(2, 10)
(2, 12)
(2, 13)
(2, 14)
(2, 15)
(2, 18)
(2, 19)
(2, 3)
(2, 16)
(2, 17)
(3, 4)
(3, 5)
(3, 6)
(3, 7)
(3, 8)
(3, 10)
(3, 12)
(3, 14)
(3, 15)
(3, 16)
(3, 19)
(3, 9)
(3, 11)
(3, 13)
(3, 17)
(4, 6)
(4, 7)
(4, 8)
(4, 9)
(4, 10)
(4, 11)
(4, 12)
(4, 13)
(4, 14)
(4, 15)
(4, 16)
(4, 19)
(4, 5)
(5, 7)
(5, 8)
(5, 9)
(5, 11)
(5, 12)
(5, 13)
(5, 15)
(5, 16)
(5, 18)
(5, 14)
(5, 19)
(6, 9)
(6, 10)
(6, 13)
(6, 14)
(6, 15)
(6, 17)
(6, 18)
(6, 19)
(6, 11)
(6, 12)
(6, 16)
(7, 8)
(7, 11)
(7, 15)
(7, 16)
(7, 17)
(7, 18)
(7, 19)
(7, 9)
(7, 10)
(7, 14)
(8, 10)
(8, 11)
(8, 12)
(8, 13)
(8, 15)
(8, 16)
(8, 17)
(8, 19)
(8, 9)
(9, 10)
(9, 11)
(9, 12)
(9, 14)
(9, 15)
(9, 17